filipdutescu/renamer.nvim

.github/workflows/ci.yaml, .github/workflows/commit_lint.yaml, .github/workflows/pr_labeler.yaml, .github/workflows/release.yaml
In order to streamline releases, a release pipeline is needed, to generate a `CHANGELOG.md` and a GitHub release.
Besides that, this PR also fixes the workflow branch triggers, to not run on every pushed commit, rather only on pull requests and pushes on branches which have an associated pull request.
Resolves GH-4
- add `.github/workflows/release.yaml`
- change the triggers for all workflows to only run on pushes and pull requests for the `master`, `develop` and `release/**` branches
Since this PR adds and modifies workflows, the CI runs provide sufficient test.
=> [Feature] Ci: Add release pipeline.

.github/pr-labeler.yml, .github/workflows/pr_labeler.yaml, .github/workflows/release.yaml
Triggers for `.github/workflows/pr_labeler.yaml` and `.github/workflows/release.yaml` do not work as intended. For the
former, labeling is triggered for pushes, not only pull requests, leading to failures. For the latter, the branch name should be `master`, as the repository does not define a `main` branch.
In order to follow the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
conventions, the `hotfix` label should also be included in the branch based labels, which is done in this commit. The step responsible for this also receives a friendlier name in this commit.
- change the triggers for `.github/workflows/pr_labeler.yaml`
- change the triggers for `.github/workflows/release.yaml`
- add the `hotfix` label
- add a friendly name for the …
=> [Hotfix] CI workflows are broken

.github/workflows/release.yaml
Changelog step fails due to no checkout.
- add the `checkout` step to the `release` workflow
Existing CI workflows suffice.
=> [Hotfix] Changelog step fails due to no checkout.

.github/workflows/release.yaml
Signed-off-by: Filip Dutescu <filip.dutescu@gmail.com>
Fetch all history in release CI.
- add `fetch-depth: 0` to the `checkout` step
Existing CI workflows suffice.
=> [Hotfix] Fetch all history in release CI

README.md, doc/renamer.txt, lua/renamer/defaults.lua
Add comments explaining all of the setup options and how they affect the popup. Update the `README.md` and `doc/renamer.txt` files in order to also contain proper documentation in the code sections.
Resolves: GH-11
- add doc comments in `lua/renamer/defaults.lua`
- update `README.md` and `doc/renamer.txt` code section docs
Tests are not required for documentation changes.
=> [Feature] Docs: `setup` - Add `setup` parameters documentation.

.github/workflows/release.yaml
To make GitHub Releases friendlier, add the project name to the release name.
Closes: GH-20
- change the release name, in `.github/workflow/release.yaml`
The test to validate will be done in the `v0.2.0` release.
=> [Feature] CI: Release - Improve GitHub Release name.

lua/renamer/init.lua, lua/tests/renamer_close_spec.lua, lua/tests/renamer_rename_spec.lua
cdb40c6 (GH-33) introduced a bug which made the cursor go 1 character back when finishing the `rename()` call (by cancellation or submission).
To fix this, the popup options also contain various information regarding the starting position (where the word starts and the cursor position at the moment of the call). This makes is easy to update `on_close()` to set the cursor at the initial position on cancellation (behaviour toggled by a new parameter).
This PR also makes it so as, upon submission of the rename, the cursor is placed at the end of the new word, by copying the current implementation of `vim.lsp.buf.rename()`. The new `_lsp_rename` method makes LSP requests in the same way Neovim implements the rename feature and uses a callback to asynchronously set the cursor position.
Fixes: …
=> [Fix] Cursor placement when finishing `rename()`.

lua/renamer/init.lua, lua/tests/renamer_close_spec.lua
In `insert` mode, when cancelling `rename()` was cancelled, the cursor is put one character ahead of its initial position, as a result of cdcdb17. This PR fixes the issue by checking for the initial mode in which `rename()` was called, for `on_close()` or by getting the current mode and checking it, for `on_submit()`.
Fixes: GH-37
- check for the `initial_mode` in `on_close` and determine whether or not to add `1` to the initial column position
- check for the current mode in `on_submit` and determine whether or not to go back an additional character (for non `insert` modes, this puts the cursor on the last character of the new word)
- add tests
Existing tests are updated to cover the new functionality and 2 new test cases are added in `lua/tests/renamer_close_spec.lua`, to check for the …
=> [Fix] Cursor position when cancelled from `insert`

lua/tests/README.md
In order to help with contribution and maintenance of the project, add a tests `README.md`, containing information regarding the frameworks used, how to run the tests and the test style used.
Closes: GH-1
- add `lua/tests/README.md`
No tests needed for documentation changes.
=> [Docs] Tests: Add tests `README.md`.

README.md, lua/renamer/init.lua, lua/tests/renamer_rename_spec.lua, plugin/renamer.vim
Add a new highlighting group, `RenamerTitle`, used to set the colour of the popup title. This option was already exposed by `plenary.nvim`'s popup component.
Closes: GH-45
- add the `RenamerTitle` to `plugin/renamer.vim`
- add the `titlehighlight` options in `renamer.rename()`
- update `README.md`
Existing tests are updated to cover the new behaviour.
=> feat(highlighting): add popup title highlighting

lua/renamer/init.lua, lua/renamer/utils.lua, lua/tests/renamer_layout_spec.lua, lua/tests/renamer_rename_spec.lua, lua/tests/utils_spec.lua
Refactor logic for `renamer._get_word_boundaries_in_line()` to give the closest word start and end positions relative to the received position in the line. Move function to `utils.get_word_boundaries_in_line()` and make tests for the new logic.
Closes: GH-43
- refactor `renamer._get_word_boundaries_in_line()` and move to `utils.get_word_boundaries_in_line()`
New test cases are defined in `lua/tests/utils_spec.lua`.
=> fix: position when word appears multiple times

doc/renamer.txt
Update the Vim help-file (`doc/renamer.txt`) to contain a section on highlights. This is needed as there is currently no way to find out what highlight groups are defined by the plugin (or which are customizable), while inside of Neovim. One might not even ever know there are any, if they would not look in the `README.md`, rather only in the vimdocs.
Closes: GH-46
- update `doc/renamer.txt`
No tests are required for documentation changes.
=> docs(highlights): add vimdocs for highlighting

lua/renamer/init.lua, lua/tests/renamer_close_spec.lua, lua/tests/renamer_rename_spec.lua
Throw error and close popup without renaming, if the new word is an empty string.
Closes: GH-57
- validate new word in `on_submit()`
A new test case is added in `lua/tests/renamer_close_spec.lua` and existing tests are updated to match new functionality.
=> fix: removed renaming as empty string

lua/renamer/init.lua, lua/tests/renamer_layout_spec.lua, lua/tests/renamer_rename_spec.lua
Offset column position to the left, when the cursor is at the end of the window. This affects the popup with and without border.
BREAKING CHANGE: If the `cword` has a length greater than the `width`, set `width` to that of the `cword`. Add default width of 0, if `title` is not set.
Closes: GH-5
- update `rename()` to offset popup position if not enough space to draw it properly
- update `rename()` to not break when `title` is not set
Existing tests are updated to cover new functionality and two new test cases are added to `lua/tests/renamer_layout_spec.lua`.
=> fix!: popup draws correctly on screen edges

lua/renamer/init.lua, lua/tests/renamer_layout_spec.lua, lua/tests/renamer_rename_spec.lua
BREAKING CHANGE: Validate if the window height and width allow for the popup to be drawn, otherwise fallback to `vim.lsp.buf.rename()` and log an error.
Closes: GH-12
- update `rename()` to fallback to `vim.lsp.buf.rename()` if there is no space to draw the popup
Existing tests are updated to cover the new functionality and new test cases are also added in `lua/tests/renamer_rename_spec.lua`.
=> fix!: fallback to LSP rename if popup cannot be drawn

README.md, doc/renamer.txt, lua/renamer/defaults.lua, lua/renamer/init.lua, lua/tests/defaults_spec.lua, lua/tests/renamer_rename_spec.lua, lua/tests/renamer_setup_spec.lua
BREAKING CHANGE: Validate padding alongside the window width and height, before drawing popup.
Closes: GH-62
- validate padding before drawing popup in `rename()`
- update docs
- update padding structure
Existing tests are updated to validate the new functionality and two new tests cases are added in `lua/tests/renamer_rename_spec.lua`.
=> fix(padding)!: validate padding before drawing popup

README.md, doc/renamer.txt, lua/renamer/defaults.lua, lua/renamer/init.lua, lua/renamer/utils.lua, lua/tests/defaults_spec.lua, lua/tests/renamer_setup_spec.lua, lua/tests/utils_spec.lua
BREAKING CHANGE: Add rename changes to the quickfix list, conditioned by a new setup parameter. Update docs to describe the new parameter.
Closes: GH-69
- add `with_qf_list` parameter to `setup()` and `renamer.defaults`
- update docs
- 
Existing tests are updated with the new functionality and new test cases are added in `lua/tests/utils_spec.lua`.
=> feat(quickfix-list)!: add changes to qf list

README.md, doc/renamer.txt, lua/renamer/defaults.lua, lua/renamer/init.lua, lua/tests/defaults_spec.lua, lua/tests/renamer_rename_spec.lua, lua/tests/renamer_setup_spec.lua
Add the `with_popup` parameter to determine whether or not to use the popup to enter the new name. If popup is disabled, use `vim.fn.input` to receive the new name.
**BREAKING CHANGE**: Fallback when popup is disabled/not able to be drawn changed from `vim.lsp.buf.rename()` to using `vim.fn.input()` to ask the user for input. This is required for:
- setting the quickfix list with the resulting changes
- preserving non-GUI input alternative, since Neovim 0.5.2+ will have
its own interface for `vim.lsp.buf.rename()`
Closes: GH-68
- add `with_popup`, which by default is `true`, to determine the way in which the user inputs the new name
- change the fallback is popup is unable to be drawn to use `vim.fn.input()`
- add `rename._input_lsp_rename()` as an alternative to the default popup UI …
=> feat!: add `with_popup` to enable/disable popup

README.md, doc/renamer.txt, lua/renamer/init.lua, lua/tests/renamer_rename_spec.lua
BREAKING CHANGE: Add options to `rename()` to allow for the popup to be empty or contain the initial word.
Closes: GH-71
- add options to `rename()`
- update docs
Existing tests are updated and new test cases are added to `lua/tests/renamer_rename_spec.lua`.
=> feat(rename)!: add option for empty popup

lua/renamer/init.lua
Move `_set_cursor_to_popup_end()` call after the `_setup_window()` call, in order to properly place the cursor at the word end, as a20b471 did not set it properly.
Closes: GH-73
- move `_set_cursor_to_popup_end()` call after the `_setup_window()` call
Existing tests cover the new behaviour.
=> fix(rename): cursor placement at word end

lua/renamer/utils.lua, lua/tests/utils_spec.lua
Remove unnecessary modification of first row, in `utils.set_qf_list()`, in order to properly populate the list.
Closes: GH-79
- remove row reassigning for the first row of a file
Existing test are update to validate the new functionality.
=> fix(qflist): first line in file was not set correctly

README.md, doc/renamer.txt, lua/renamer/defaults.lua, lua/renamer/init.lua, lua/renamer/mappings/init.lua, lua/tests/defaults_spec.lua, lua/tests/mappings/mappings_defaults_spec.lua, lua/tests/mappings/mappings_exec_keymap_action_spec.lua, lua/tests/mappings/mappings_register_bindings_spec.lua, lua/tests/renamer_setup_spec.lua
This PR adds two new changes, related to GH-84:
---
BREAKING CHANGE: Add a new field, `handler`, representing a function to be called after successful renames, with the LSP `textDocument/rename` raw response.
Closes: GH-84
---
BREAKING CHANGE: TODO integrate `nvim-notify`
- add `handler` field to be called with the LSP raw response on successful renames
- update docs
Existing tests are updated to validate the new functionalities and new test cases are added for each new behaviour.
=> feat!: add custom handler for successful renames

README.md, doc/renamer.txt, lua/renamer/init.lua
Add missing `,` in various Lua snippets found in docs.
- update docs
No tests needed for documentation changes.
=> docs: fix Lua in docs

lua/renamer/init.lua
Handle LSP rename responses containing `documentChanges`, as some servers only provide this field and for those that provide it as well as `changes`, `documentChanges` should be prefered, as indicated by the [LSP documentation][lsp-rename-docs].
Refs: GH-84
[lsp-rename-docs]:
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/
- handle `documentChanges` in LSP response, in `renamer._lsp_rename()`
Existing tests cover the new behaviour.
=> fix(rename): handle `documentChanges` LSP response

lua/renamer/init.lua, lua/renamer/utils.lua
The fix for GH-84 introduced a bug for LSP servers that provide the `documentChanges` field, making the quickfix list not be set.
References: GH-84
- send the proper field in the `set_qf_list` call in `on_submit()`
- properly set changes for responses containing `documentChanges`
Existing tests cover the functionality.
=> fix: responses with `documentChanges` set qflist properly

lua/tests/utils_spec.lua
Changes made by 645e7bd lead to one test case for `set_qf_list()` to fail. This commit fixes the broken test to match the new functionality.
References: GH-90
- update the failing test case in `lua/tests/utils_spec.lua`
Since this PR fixes tests, if the CI passing covers the changes.
=> tests(qf-list): fix failing tests

lua/renamer/constants.lua, lua/renamer/init.lua, lua/tests/renamer_close_spec.lua, lua/tests/renamer_layout_spec.lua, lua/tests/renamer_rename_spec.lua
Prevent renaming when no LSP client is attached to the current buffer.
Overhaul tests to cover the renaming logic.
Closes: GH-96
- update `renamer.rename()` to only allow renaming when an LSP client is attached
Existing tests are updated to cover the new functionality and new tests are added for the overhaul covering `renamer._lsp_rename()`.
=> fix: popup showing when no LSP client attached

README.md, doc/renamer.txt, lua/renamer/defaults.lua, lua/renamer/init.lua, lua/tests/defaults_spec.lua
Add `minwidth` and `maxwidth` default and setup parameters in order to allow for customizable size of the popup.
Closes: GH-101
- add `minwidth` and `maxwith` to `lua/renamer/defaults.lua`
- add `minwidth` and `maxwith` to `lua/renamer/init.lua` (in `setup(...)`)
- update docs
Existing tests cover the new changes.
=> feat: add customizable min and max width

lua/renamer/init.lua, lua/tests/renamer_layout_spec.lua
Fix an issue that made the popup render improperly when the file contained a low number of lines (< 5), but the window high was high enough.
Closes: GH-105
- flip line position only if there is not enough space to draw the popup below in the window
Existing tests were updated to validate the new functionality and new ones were added in `lua/tests/renamer_layout_spec.lua`.
=> fix(layout): popup position when low number of lines

lua/renamer/init.lua
Add default value if `resp.changes` is `nil`, in order to not break response handling if an LSP response does not provide that field.
Closes: GH-106
- add default value of `{}` if `resp.changes` is `nil` in `_lsp_rename(...)`
Not sure what the proper way to implement a test specifically for this is. TBD.
=> fix(rename): responses without `changes` break `qflist`

lua/renamer/utils.lua
If the word to be renamed is present or is in the body of another word on the same line, the popup could've been prevented from being shown, due to the use of an `and` condition instead of an `or` one in `utils.get_word_boundaries_in_line(...)`.
Closes: GH-113
- change `and` condition to `or`
Existing tests cover the functionality.
=> fix: popup not showing if renamed word appears twice

lua/renamer/constants.lua, lua/renamer/init.lua, lua/tests/renamer_layout_spec.lua
The popup would have the `sidescrolloff` set in Neovim's config, leading to words being truncated and looking off. Now the setting is put to 0 for the popup window to prevent the issue.
There was also an issue with the width of the popup if the word to be renamed was larger than the default width, which lead to 1 character being truncated. This was fixed by adding `+ 1` to the word length.
Closes: GH-101
- set `sidescrolloff` to 0 in `_setup_window`
- add `+ 1` to the current word length when setting the popup width based on it
- add constant for `sidescrolloff`
Existing tests are updated to validate the new functionality.
=> fix: popup having `sidescrolloff` if set

.gitignore, lua/renamer/constants.lua, lua/renamer/init.lua, lua/tests/renamer_close_spec.lua, lua/tests/renamer_rename_handler_spec.lua
BREAKING CHANGE: Migrate the LSP buffer request from manual to using `vim.lsp.buf.rename(...)` to make the request and a custom LSP response handler to manage the custom response processing (eg setting the qf list) and the original Neovim rename handler to apply the requested changes.
This implies removing several existing function, doing some cleanup of tests and updating the documentation.
Fixes: GH-117, fixes: GH-121
- remove all buffer requests method
- update `renamer._setup(...)` to change the default rename handler to the custom one 
- add custom handler
- add custom handler test spec (`lua/tests/renamer_rename_handler_spec.lua`)
Existing tests are updated to match the new functionality and a new spec is added to test the custom handler.
=> feat(handler): migrate to handler

lua/renamer/init.lua, lua/tests/renamer_close_spec.lua, lua/tests/renamer_rename_handler_spec.lua
Trim the new word of leading and ending spaces before using it to rename. This should prevent padding from being used in the final name, as well as making it a bit more logic and consistent with most IDEs.
Fixes: GH-119
- trim `new_word` spaces on submit (as seen in [this StackOverflow question](https://stackoverflow.com/a/51181334))
- radd a test case to validate the change
Existing tests are updated and a new test case is added in `lua/tests/rename_close_spec.lua`.
=> fix(submit): trim new word before using
